language: node_js
node_js:
  - "6"
addons:
  chrome: stable
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
