os: linux
language: node_js
node_js:
  - "6"
env: DISPLAY=':99.0'
addons:
  chrome: stable
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_success: never
