language: node_js
node_js:
  - "6"
dist: trusty
sudo: false
cache: npm
before_install:
  - sudo apt -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel
notifications:
  email:
    on_success: never
