language: node_js
node_js:
  - "6"
dist: trusty
addons:
  apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
sudo: false
cache: npm
notifications:
  email:
    on_success: never
